### ISSUE TITLE
use "axis" not "axe" :)

### ISSUE THREAD

**Issue by zethussuen** [lucaorio/sketch-reverse#1]
>Sketch Reverse is a plugin made for Sketch. It reverses the position of multiple elements on the x or y axe, without changing the layers' depth/order.

singular: axis
plural: axes

**Comment by lucaorio** [comment]
HAHAHA, thanks for the heads up man, I made the mistake once and copy pasted it everywhere. At least it's a funny one 😂

**Comment by zethussuen** [comment]
![image](https://user-images.githubusercontent.com/754158/38433853-63ccb0b6-399a-11e8-826b-3be7ba87123b.png)

**Comment by zethussuen** [comment]
it's okay luca. you're an italian ex-rocker. such typos are to be expected.

**Comment by lucaorio** [comment]
@zethussuen LOL! I just pushed the fixes, thanks again! :D
![bm11](https://user-images.githubusercontent.com/299621/38439036-1fff582e-3991-11e8-8562-409f52aee4c8.jpg)
